### ISSUE TITLE
On Mac OSX Moutain Lion JpegMINI is not applied

### ISSUE THREAD

**Issue by benjamin74** [ramiroaraujo/alfred-image-optim-workflow#2]
Hello,

I've followed the installation process (including enabling access to assistive devices which is needed) but when running through a bunch of files : png and JPG then the JPG files are almost not compressed at all and clearly aren't handled by JpegMINI.

Any idea where it comes from ?

Thanks,

Cheers,

**Comment by ramiroaraujo** [comment]
just FYI, this is no longer relevant as the workflow no longer users jpegmini :)
